const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const source=fs.readFileSync(path.join(__dirname,'../web/app.js'),'utf8');
const begin=source.indexOf('function geometryFromDraft('),end=source.indexOf('\nfunction renderSurveyCoverage',begin);
const context={};vm.createContext(context);vm.runInContext(source.slice(begin,end),context);
const parse=(draft,group={needs_waypoints:true})=>JSON.parse(JSON.stringify(context.geometryFromDraft(draft,group)));
const points='7.3, 2.4, 0.9\n8.9, 2.4, 0.9\n8.9, 2.3, 0.9\n8.9, 1.3, 0.9\n8.9, 0.2, 0.9\n8.9, -0.8, 0.9\n8.9, -2.3, 0.9';
const base={geometryPoints:points,geometryLanding:'8.9, -2.3',geometryAxis:'1',geometryWalls:'1.8, -0.3',geometryEntry:'1'};
assert.equal(parse(base).corridor_waypoints.length,7);
assert.deepStrictEqual(parse(base).corridor_waypoints[6],{x:8.9,y:-2.3,agl:.9});
assert.deepStrictEqual(parse({...base,geometryPoints:points.replace(/\n/g,'\r\n')}),parse(base));
assert.deepStrictEqual(parse({...base,geometryPoints:'\n'+points+'\n\n'}),parse(base));
assert.deepStrictEqual(parse({...base,geometryPoints:points.replace(/, /g,'\t')}),parse(base));
assert.deepStrictEqual(parse({...base,geometryPoints:points.replace(/,/g,'，')}),parse(base));
assert.throws(()=>parse({...base,geometryPoints:'1,2,0.9\n3,4'}),/第2行.*需要3个数/);
assert.throws(()=>parse({...base,geometryLanding:''}),/H中心.*需要2个数/);
assert.throws(()=>parse({...base,geometryLanding:'[8.9, -2.3]'}),/H中心.*括号/);
assert.throws(()=>parse({...base,geometryPoints:'1,2,NaN\n3,4,0.9'}),/第1行.*有限数值/);
assert.throws(()=>parse({...base,geometryArea:'{bad}'}),/flight_area.*JSON/);
assert.deepStrictEqual(parse({...base,surveyEnabled:false,surveyBounds:'bad'}),parse(base));
const survey={surveyEnabled:true,surveyBounds:'0.4,7.4,-2.4,2.4',surveyInset:0,surveyCameraHeight:'2',surveyOffset:'-0.16',surveyFovX:'60',surveyFovY:'80'};
assert.equal(parse({...base,...survey}).survey_plan.inset,0);
assert.throws(()=>parse({...base,...survey,surveyBounds:'1,2'}),/搜索区范围.*需要4个数/);
assert.throws(()=>parse({...base,...survey,surveyFovX:''}),/任务X方向视场角/);
assert(parse({...survey,geometryPoints:'hidden malformed field'},{needs_waypoints:false}).survey_plan);
console.log('coordinate draft parser: 16 checks PASS');